### ISSUE TITLE
Writeback bug

### ISSUE THREAD

**Issue by efthym** [chrysko/ptyxiaki#1]
Παρατήρησα ότι δεν έχεις κάποιο σήμα που επιτρέπει την εγγραφή κάποιου καταχωρητή στο register file. Στην αρχή νόμιζα ότι υπήρχε μεγάλο πρόβλημα γιατί πολλές εντολές δεν γράφουν αποτέλεσμα σε καταχωρητή (π.χ. η sw), αλλά τελικά πρόσεξα ότι στο mux2x1_5bit.v, γραμμή 17 όλες οι εντολές που δεν γράφουν σε καταχωρητή, "γράφουν" στον καταχωρητή 0 και όταν διαβάζεται ο καταχωρητής 0 δίνει πάντα 0.
Αλλά, το mux2x1_5bit έχει ένα λάθος για add immediate: δεν θα έπρεπε να ελέγχει τον in1 αλλά το in2. Η εντολή αυτή γράφει αποτέλεσμα στον rt.

**Comment by chrysko** [comment]
Ναι, το βρήκα το πρόβλημα. Έμενε απο την μεταφορά στο ξεχωριστό αρχείο. Τουλάχιστον για όσα δοκίμασα δουλεύει σωστά τώρα.
